common: &common
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost

development:
  <<: *common
  database: sharetravel_development

test:
  <<: *common
  database: sharetravel_test

production:
  <<: *common
  database: sharetravel_development
